### ISSUE TITLE
upgrade protobuf compiler and library to 2.5.0

### ISSUE THREAD

**Issue by simonandluna** [twitter/elephant-bird#358]
It seems current elephand-bird still uses 2.4.1 protobuf compiler and library, which was 2.5 years old. We are currently using 2.5.0 protobuf library in our project. Unfortunately, library of 2.5.0 does not fully support auto-generated protobuf java codes using 2.4.1 compiler.

This caused an issue when we tried to use SerializedBlock class in block_storage.proto. Error messages look like:

java.lang.UnsupportedOperationException: This is supposed to be overridden by subclasses at com.google.protobuf.GeneratedMessage.getUnknownFields(GeneratedMessage.java:180) at com.twitter.data.proto.BlockStorage$SerializedBlock.getSerializedSize(BlockStorage.java:164) at com.google.protobuf.AbstractMessageLite.toByteArray(AbstractMessageLite.java:62)

Will you consider to upgrade protobuf compiler and library in elephandbird?

**Comment by stark-summer** [comment]
I have this problem too,As my project already running so long time,but recently, I need to add new fuction,when I ready to running this project  in my cluster hadoop envroment,this problem is comming~

**Comment by osDanielLee** [comment]
My code counts on this problem recently,how could I fix it,pls?

**Comment by osDanielLee** [comment]
It makes me mad
