### ISSUE TITLE
Error in Front Page Documentation

### ISSUE THREAD

**Issue by phui** [twitter/elephant-bird#451]
at here:

https://github.com/twitter/elephant-bird#quickstart

the doc recommends readers to download elephant-bird from a wrong repo:

    git clone git://github.com/kevinweil/elephant-bird.git

It should instead be

    git clone git://github.com/twitter/elephant-bird.git

**Comment by rubanm** [comment]
Closed by https://github.com/twitter/elephant-bird/pull/460
